name: The typography blog
favicon: null
layout_spectrum: 0.22496852627955377
typography_spectrum: 0.12547230860218406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.06538033811375499
  lightness: 0.6313297387678176
  saturation: 0.6659995925147086
  rhythmicContrast: 0.8851769147440791
purpose: []
